task:
  name: FreeBSD 12 amd64 stable
  freebsd_instance:
    image: freebsd-12-1-release-amd64
    cpu: 1
    memory: 1 # GB
  env:
    RUST_BACKTRACE: 1
    RUSTFLAGS: --cfg features="os-poll"
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  build_script:
    - . $HOME/.cargo/env
    - cargo check --tests --examples
    - cargo check --features mio --tests --examples
    - cargo check --features mio-uds --tests --examples
    - cargo check --features mio_07 --tests --examples
    - cargo check --features tokio --tests --examples
    - cargo build --all-features --tests --examples
  test_script:
    - . $HOME/.cargo/env
    - cargo run --bin characteristics
    - cargo test --all-features --no-fail-fast
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index

task:
  name: Linux amd64 1.39
  container:
    image: rust:1.39
    cpu: 1
    memory: 1
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  build_script:
    - cargo check
    - cargo check --features mio
    - cargo check --features mio-uds
    - cargo check --features mio_07
    - cargo check --features tokio
    - cargo build --all-features
  test_script:
    - cargo run --bin characteristics
    - export RUSTFLAGS='--cfg features="os-poll"'
    - cargo test --all-features --no-fail-fast -- --test-threads=1
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index

task:
  name: Linux amd64 nightly minimal-versions
  container:
    image: rustlang/rust:nightly
    cpu: 1
    memory: 1
  allow_failures: false
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  build_script:
    - cargo check -Z minimal-versions
    - cargo build -Z minimal-versions --features mio
    - # no version of mio-uds compiles
    - cargo build -Z minimal-versions --features mio_07
    - cargo build -Z minimal-versions --features tokio
  test_script:
    - RUST_BACKTRACE=1
    - cargo test -Z minimal-versions --features mio --no-fail-fast -- --test-threads=1
    - export RUSTFLAGS='--cfg features="os-poll"'
    - cargo test -Z minimal-versions --features mio_07 --no-fail-fast -- --test-threads=1
    - cargo test -Z minimal-versions --features tokio --no-fail-fast -- --test-threads=1
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index

task:
  name: Linux i686 stable
  container:
    image: rust:latest
    cpu: 1
    memory: 1
  allow_failures: false
  env:
    RUST_BACKTRACE: 1
    RUSTFLAGS: --cfg features="os-poll"
  setup_script:
    - apt-get update
    - apt-get install -yqq gcc gcc-multilib linux-libc-dev
    - rustup target add i686-unknown-linux-gnu
    - rustup target add i686-unknown-linux-musl
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  build_script:
    - cargo build --target i686-unknown-linux-gnu --all-features
    - cargo build --target i686-unknown-linux-musl --all-features
  test_script:
    - export RUSTFLAGS='--cfg features="os-poll"'
    - cargo test --target i686-unknown-linux-gnu --all-features --no-fail-fast -- --test-threads=1
    - cargo test --target i686-unknown-linux-musl --all-features --no-fail-fast -- --test-threads=1
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index

task:
  name: Cross-check stable
  container:
    image: rust:latest
    cpu: 1
    memory: 1
  allow_failures: false
  env:
    RUSTFLAGS: --cfg features="os-poll"
  setup_script:
    - rustup target add x86_64-unknown-netbsd
    - rustup target add x86_64-sun-solaris
    - rustup target add x86_64-unknown-linux-gnux32
    - rustup target add aarch64-unknown-linux-gnu
    - rustup target add aarch64-linux-android
    - rustup target add x86_64-pc-windows-msvc
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock 2> /dev/null || true
  build_script:
    - cargo check --target x86_64-unknown-netbsd --all-features --tests
    - cargo check --target x86_64-sun-solaris --tests
    - cargo check --target x86_64-unknown-linux-gnux32 --all-features --tests
    - cargo check --target aarch64-unknown-linux-gnu --all-features --tests
    - cargo check --target aarch64-linux-android --all-features --tests
    - cargo check --target x86_64-pc-windows-msvc --all-features --lib
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index
