language: rust
rust: stable
env: RUST_BACKTRACE=1

script:
  - cargo run --bin characteristics
  - cargo check
  - cargo check --features mio
  - cargo check --features mio-uds
  - cargo check --features mio_07
  - cargo check --features tokio
  - export RUSTFLAGS='--cfg feature="os-poll"'
  - cargo test --all-features --no-fail-fast

jobs:
  include:
  - name: "macOS stable"
    os: osx
    arch: amd64
  - name: "Linux amd64 stable"
    os: linux
    arch: amd64
  - name: "Linux aarch64 stable"
    os: linux
    arch: arm64
  - name: "Linux ppc64le stable"
    os: linux
    arch: ppc64le
  # - name: "Linux s390x stable"
  #   os: linux
  #   arch: s390x
  # - name: "Windows stable"
  #   os: windows
  #   arch: amd64
