[package]
name = "uds"
version = "0.0.0"
description = """
A unix domain socket crate that supports abstract addresses, fd-passing and seqpacket sockets.
Only tested on Linux.
"""
readme = "README.md"
repository = "https://github.com/tormol/uds"
license = "Apache-2.0 / MIT"
authors = ["Torbjørn Birch Moltu <t.b.moltu@lyse.net>"]
keywords = ["unix-domain", "socket", "SOCK_SEQPACKET", "abstract-address", "fd-passing"]
categories = ["os::unix-apis", "asynchronous"]
edition = "2018"
exclude = ["tests", "src/bin"]

[target."cfg(unix)".dependencies]
libc = "0.2.59" # .59 added FIONCLEX for Linux
# enabling this feature implements the extension traits for mio-uds types
mio-uds = {version="0.6", optional=true} # no patch release builds with -Z minimal-versions
# enabling this feature implements Evented for this crate's non-blocking seqpacket types
mio = {version="0.6.14", optional=true} # .14 avoids dragging in libc 0.1 under -Z minimal-versions

[package.metadata.docs.rs]
features = ["mio-uds", "mio"]
