[package]
name = "ud3"
version = "0.0.0"
readme = "README.md"
repository = "https://github.com/tormol/ud3"
license = "Apache-2.0 / MIT"
authors = ["Torbjørn Birch Moltu <t.b.moltu@lyse.net>"]
keywords = ["uds", "unix domain", "socket", "abstract"]
categories = ["os::unix-apis"]
edition = "2018"

[dependencies]
libc = "0.2.59" # .59 added FIONCLEX for Linux
# implements the extension traits for mio-uds's types
mio-uds = {version="0.6", optional=true} # no patch release builds with -Z minimal-versions
