[package]
name = "uds"
version = "0.2.2"
description = """
A unix domain socket crate that supports abstract addresses, fd-passing and seqpacket sockets.
"""
readme = "README.md"
repository = "https://github.com/tormol/uds"
license = "Apache-2.0 / MIT"
authors = ["Torbjørn Birch Moltu <t.b.moltu@lyse.net>"]
keywords = ["unix-domain", "socket", "SOCK_SEQPACKET", "abstract-address", "fd-passing"]
categories = ["os::unix-apis", "asynchronous"]
edition = "2018"
exclude = ["tests", "src/bin"]

[features]
tokio = ["futures", "mio", "tokio_02"]

[target."cfg(unix)".dependencies]
libc = "0.2.75" # .75 added peer credentials functions and types for solarish
# enabling this feature implements the extension traits for mio-uds types
mio-uds = {version="0.6", optional=true} # no patch release builds with -Z minimal-versions
# enabling this feature implements Evented for this crate's non-blocking seqpacket types
mio = {version="0.6.14", optional=true} # .14 avoids dragging in libc 0.1 under -Z minimal-versions
# enabling this feature implements the extension traits for mio 0.7's unix socket types
# and Source for this crate's non-blocking seqpacket types.
mio_07 = {package="mio", version="0.7.0", features=["os-util", "uds"], optional=true}
# examples and tests for mio_07 also requires mio feature os-poll,
# but adding it as a dev-dependency would also enable it in all cases (cargo bug #4866)
# instead RUSTFLAGS='--cfg feature="os-poll"' must be used to build & run mio_07 tests
futures = {version = "0.3", optional=true}
tokio_02 = {package="tokio", version = "0.2", features = ["io-driver"], optional=true}

[target."cfg(unix)".dev-dependencies]
remove_dir_all = "=0.5.2" # Avoids MSRV bump (Stebalien/tempfile#120)
tempfile = "3.1"
tokio_02 = {package="tokio", version = "0.2", features = ["macros", "rt-core"]}

[package.metadata.docs.rs]
features = ["mio-uds", "mio", "mio_07", "tokio"]
rustdoc-args = ["--cfg", "feature=\"os-poll\""]
